source 'https://rubygems.org'

gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-sprockets'
gem 'middleman-autoprefixer'
gem 'middleman-blog'
gem 'middleman-syntax'
gem 'bitters'
gem 'bourbon'
gem 'neat'
gem 'nokogiri'
gem 'redcarpet'
