source 'https://rubygems.org'
ruby "2.3.0"

gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-sprockets'
gem 'middleman-autoprefixer'
gem 'middleman-blog'
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'middleman-syntax'
gem 'bitters'
gem 'bourbon'
gem 'neat'
gem 'nokogiri'
gem 'redcarpet'
